### ISSUE TITLE
SigScan not working

### ISSUE THREAD

**Issue by Aboba7778** [Yimura/gtav-sigscan-action#3]
### **Describe the bug** 
Sigscan not working. I forked sigscan repository and run action (Test Local Github Action) with detected.dll.
Result: No detections found, doing nothing...

### **Steps To Reproduce**
Run scan action.
### **Expected Behavior**
Result: dll detected.

**Comment by Yimura** [comment]
Rockstar removes the detections with each update so the detected.dll is no longer detected.

You can dump the JSON file to see which strings and byte arrays are detected with the current update.
